### ISSUE TITLE
review Dashboard lesson

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn_field_reporting_standards#12]
https://ocean-tracking-network.github.io/otn_field_reporting_standards/06-KPIdashboard/index.html 

addd ur thoughts here and i can do the edits

**Comment by SoftwareMonk** [comment]
You are able to export as either a CSV or XLSX.

This isn't true but [I'm gonna make it true.](https://gitlab.oceantrack.org/otndc/kpi-dashboard/-/issues/28)

**Comment by SoftwareMonk** [comment]
No other lies :stuck_out_tongue_closed_eyes: good to publish
