### ISSUE TITLE
review Snipe lesson

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn_field_reporting_standards#13]
please review https://ocean-tracking-network.github.io/otn_field_reporting_standards/03-inventory/index.html 

add comments here ill make the changes

**Comment by bmanjones** [comment]
Do you want me to add a template to the: TODO add template section?

**Comment by CaitlinBate** [comment]
nope, i have the template just have to upload it haha thanks tho! #9 has my TODOs in it

**Comment by bmanjones** [comment]
I have no notes. Everything looks great 👍 Snipe is due for an upgrade but we can schedule that at a later time and update the documentation if needed.
