### ISSUE TITLE
outstanding

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn_field_reporting_standards#9]
- [x] add any pics/screenshots
- [x] finish any TODOs
- [x] edit ppt thats linked
- [x] final content review

**Comment by naomitress** [comment]
- ppt https://github.com/ocean-tracking-network/otn_field_reporting_standards/blob/gh-pages/files/ONC_workshop_2022_04.pptx

- **DONE** todo https://github.com/ocean-tracking-network/otn_field_reporting_standards/blob/7ef8f15c90115617d38f2dea01c3564557b379b3/_episodes/03-inventory.md?plain=1#L64

- todo https://github.com/ocean-tracking-network/otn_field_reporting_standards/blob/7ef8f15c90115617d38f2dea01c3564557b379b3/_episodes/04-ROV.md?plain=1#L31
- todo https://github.com/ocean-tracking-network/otn_field_reporting_standards/blob/7ef8f15c90115617d38f2dea01c3564557b379b3/_episodes/04-ROV.md?plain=1#L46

**Comment by naomitress** [comment]
@CaitlinBate where were you thinking for pics?

**Comment by CaitlinBate** [comment]
content edited lessons 00 and 01, committed locally. stepping away so wanna make sure i track what i did for when i come back haha
